[workspace.package]
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/sha-p2pool"
license = "BSD-3-Clause"
version = "1.0.1"
edition = "2021"


[workspace]

members = ["p2pool", "integration_tests", "stratum"]


# Add here until we move to edition=2021
resolver = "2"


[workspace.dependencies]
anyhow = "1.0"
tari_shutdown = { git = "https://github.com/tari-project/tari.git", rev = "b5da6e87d9d32532b76f2c25221c540db4f51ef3" }
log = { version = "0.4.21", features = ["kv"] }
tokio = { version = "1.41.0", features = ["full"] }

serde_json = "1.0.122"

[profile.release]
overflow-checks = true
opt-level = 3
debug = false
# To enable debug symbols with dhat profiling in release mode, enable the 'dhat-heap' feature and use
# CARGO_PROFILE_* Environment Variables:
#   CARGO_PROFILE_RELEASE_DEBUG=true cargo build --release --features=dhat-heap               ...(Linux)
#   $env:CARGO_PROFILE_RELEASE_DEBUG = "true"; cargo build --release --features=dhat-heap     ...(PowerShell)
