[workspace.package]
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/sha-p2pool"
license = "BSD-3-Clause"
version = "0.25.3-rc.0"
edition = "2021"


[workspace]

members = ["p2pool", "integration_tests"]

# Add here until we move to edition=2021
resolver = "2"


[profile.release]
overflow-checks = true
opt-level = 3
debug = false
# To enable debug symbols with dhat profiling in release mode, enable the 'dhat-heap' feature and use
# CARGO_PROFILE_* Environment Variables:
#   CARGO_PROFILE_RELEASE_DEBUG=true cargo build --release --features=dhat-heap               ...(Linux)
#   $env:CARGO_PROFILE_RELEASE_DEBUG = "true"; cargo build --release --features=dhat-heap     ...(PowerShell)
